### ISSUE TITLE
RUN causes a segfault on Ubuntu?

### ISSUE THREAD

**Issue by jtint24** [Minxrod/sbc#1]
First of all, I want to say that this is an amazing project and the progress on it already is amazing. I've been trying to get it set up for myself locally, but I've hit a snag.

The REPL seems to work fine for me. FILES, PRINT, LOCATE, and CLS seem to work as expected, as well as the mathematical functions. But I can't seem to be able to load a file. Syntax like `LOAD "FILENAME"` doesn't work, but `LOAD "PRG:FILENAME"` seems to work fine. Unfortunately, when I try to use RUN, the interpreter hits a segfault. I'm curious if I'm using the commands incorrectly or if there's a way around this.

LOAD result:
![Screenshot 2024-06-24 at 5 51 40 PM](https://github.com/Minxrod/sbc/assets/89891042/3db862d6-04f3-4a07-a1be-e9cbb95cafe4)

FILES result:
![Screenshot 2024-06-24 at 5 51 50 PM](https://github.com/Minxrod/sbc/assets/89891042/eae434a6-7ec2-4898-bf27-98a2eea7a073)

Logs:
After running LOAD and then RUN:
![Screenshot 2024-06-24 at 5 50 02 PM](https://github.com/Minxrod/sbc/assets/89891042/cb525abe-3d53-4c6c-b473-509779efc523)
![Screenshot 2024-06-24 at 5 50 28 PM](https://github.com/Minxrod/sbc/assets/89891042/9c6b6499-6884-4b9a-a86b-74cd45471a3e)

**Comment by Minxrod** [comment]
I think I might've broke it sometime in the last couple of updates, as it segfaults on my (Debian) machine too. I'll try to fix it this weekend, but as a workaround you might be able to use `EXEC` instead, as that one still works when I test it.

**Comment by jtint24** [comment]
Amazing! Exec works great

**Comment by Minxrod** [comment]
Going to leave this open until I fix `RUN`, since it is an issue that it doesn't currently work.

**Comment by Minxrod** [comment]
Should be fixed now, in latest version.
